### ISSUE TITLE
kubernetes version doc says generate but no file

### ISSUE THREAD

**Issue by ksully-execute** [jenkins-x/jx-cli#1114]
On https://jenkins-x.io/v3/admin/platforms/on-premise/
References a quickstart, with this link; https://github.com/jx3-gitops-repositories/jx3-kubernetes/generate
which doesn't exist (no generate file)

**Comment by ksully-execute** [comment]
﻿When I use that URL you listed: https://github.com/jx3-gitops-repositories/jx3-kubernetes/generate

It worked and generated me a repo….not sure why that works…

 

From: James Strachan ***@***.***>
Reply-To: jenkins-x/jx-cli ***@***.***>
Date: Tuesday, March 30, 2021 at 9:13 AM
To: jenkins-x/jx-cli ***@***.***>
Cc: ksully-execute ***@***.***>, Author ***@***.***>
Subject: Re: [jenkins-x/jx-cli] kubernetes version doc says generate but no file (#1114)

 

not sure I understand - the URL works for me? https://github.com/jx3-gitops-repositories/jx3-kubernetes/generate

what do you get when you navigate to https://github.com/jx3-gitops-repositories/jx3-kubernetes/generate - do you see the github generate template page for the git repository https://github.com/jx3-gitops-repositories/jx3-kubernetes?

any chance of a screen grab of your web browser? could it be firewall issues or browse cache problems I wonder?

**Comment by jstrachan** [comment]
ah - I wonder if the reason it didn't work is you were not logged into GitHub at the time? I'll update the docs to make sure that if the generate URL fails it could be due to you not being logged into github

**Comment by jstrachan** [comment]
I've modified the website to explicitly say that if the generate button doesn't work make sure you are logged into github:
https://jenkins-x.io/v3/admin/platforms/on-premise/#getting-started

hopefully that fixes it for you and others!

**Comment by ksully-execute** [comment]
﻿Thanks!

 

From: James Strachan ***@***.***>
Reply-To: jenkins-x/jx-cli ***@***.***>
Date: Wednesday, March 31, 2021 at 9:24 AM
To: jenkins-x/jx-cli ***@***.***>
Cc: ksully-execute ***@***.***>, Author ***@***.***>
Subject: Re: [jenkins-x/jx-cli] kubernetes version doc says generate but no file (#1114)

 

I've modified the website to explicitly say that if the generate button doesn't work make sure you are logged into github:
https://jenkins-x.io/v3/admin/platforms/on-premise/#getting-started

hopefully that fixes it for you and others!
