### ISSUE TITLE
Give mac users an option to install using brew

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-cli#176]
JenkinsX 2 mac users could download the binary using brew. I think we should also add that for JX3.

**Comment by jstrachan** [comment]
in the early days of jx we supported lots of different tools to install binaries like brew/chocolate etc. 

increasingly with the version stream its nicer to get jx to be in full control over the exact versions of everything in one place (e.g. updating the version stream with 1 commit could upgrade the recommended versions of jx + helm).

when using things like brew, its more complex as each binary has its own recipe and syncing the version stream + brew recipe's can be harder.

So I'd be tempted for linux + mac to get folks to just copy/paste 2 lines of bash from the website like these...
https://github.com/jenkins-x/jx-cli/releases/tag/v3.0.16

then we know jx is just a binary somewhere on the $PATH so its super easy for jx to upgrade itself again later without the extra complexities of dealing with brew.

we could revisit in the future though once everything's rocking

**Comment by jstrachan** [comment]
mind you - having said all of that - having boot run a Job inside k8s means we're much less `jx` version dependent than we used to be. Moving most stuff to run inside k8s where possible - and developers mostly just change git - really helps simplify all this complexity

**Comment by jstrachan** [comment]
gonna close this - as its gonna be better jx managing versions of itself and plugins rather than a separate package manager (its very hard to align them all together)
