### ISSUE TITLE
jx upgrade plugins fails on Windows 10

### ISSUE THREAD

**Issue by paigashaona** [jenkins-x/jx-cli#612]
The CLI fails to update its plugins running under Windows 10 without WSL or other linux-centric dev tools installed

```
> jx upgrade plugins
checking binary jx plugin admin version 0.0.137 is installed
Installing plugin jx-admin version 0.0.137 for command jx admin from https://github.com/jenkins-x/jx-admin/releases/download/v0.0.137/jx-admin-windows-amd64.zip into C:\Users\xxx\.jx3\plugins\bin
error: failed to ensure plugin is installed admin: open C:\Users\xxx\AppData\Local\Temp\jx-admin461013463\jx-admin: The system cannot find the file specified.
```

The folder is being created successfully in the temp directory, with the downloaded zip inside, but it seems like it is not getting unzipped, potentially. I don't however enough experience with go to have a better idea than that of why it's broken.

**Comment by jstrachan** [comment]
this should now be fixed; we had a Windows specific bug downloading and installing plugins which is now fixed + we've a unit test to verify it keeps working on windows
