### ISSUE TITLE
jx admin operator installation fails on Windows Operating System ( Windows 10 )  | jx-admin: The system cannot find the file specified.

### ISSUE THREAD

**Issue by udomsak** [jenkins-x/jx-cli#653]
## OS: 
-  Windows 10 64bit

## Jx Version
``` version: 3.0.755 ```

## Command usage:
```  jx admin operator ``` 

## Resolve: 
* Fix by manual (download from release page then extract to ```.jx3\plugins\bin``` folder).

## RelateBug: 
* Golang [The system cannot find the path specified](https://github.com/golang/go/issues/24968) ||  [os: IsDir doesn't work with Windows OneDrive #22579](https://github.com/golang/go/issues/22579)

## Errorlog: 
```
C:\Users\Admin\Documents\Omylab\jx3-kubernetes>jx admin operator
Installing plugin jx-admin version 0.0.140 for command jx admin from https://github.com/jenkins-x/jx-admin/releases/download/v0.0.140/jx-admin-windows-amd64.zip
into C:\Users\Admin\.jx3\plugins\bin
ERROR: failed to install binary plugin jx-admin version 0.0.140 to C:\Users\Admin\.jx3\plugins\bin: open C:\Users\Admin\AppData\Local\Temp\jx-admin689165427\jx-admin: The system cannot find the file specified.

```

**Comment by jstrachan** [comment]
I think this is fixed now; it was a windows bug in the jx plugins. We've a unit test to verify this all works on windows + linux
